Kellychanges
tangkelly1999/website pull request #5
Opened 2019-02-27 01:46 UTC by tangkelly1999

I made more changes. How do i format the pictures better it looks weird when i change the screen size. where do you think i should put like a link for my resume. Any suggestions/comments to style and layout would be quite valuable. Thanks bud!

2019-02-27 01:48 UTC, tangkelly1999 commented
also pls help me make my description sound more like i know stuff :)

2019-02-28 15:12 UTC, andyjiin requested changes
First of all, why do you have a bunch of random screenshots. And secondly I would make the images much bigger. And do you like the font?

2019-02-28 15:17 UTC, andyjiin requested changes

2019-02-28 15:17 UTC, andyjiin commented on main.html
> +        <div class="subheading mb-5"> University of Waterloo | Electrical Engineering Student </div>
nice flex

2019-02-28 15:17 UTC, andyjiin commented on main.html
> +        Hello there! I'm Kelly and I'm an engineering student at the University of Waterloo. My design experience ranges from PCB design to power distribution (grammar?). I'm interested in ???. Curre
bad change I like what it said before hehe. But this page is very empty we can work on it later

2019-02-28 15:17 UTC, andyjiin commented on stylesheet.css
> +  color: #FFF0F5;
You can barely see the title colours are you going to change the background color as well?

2019-02-28 15:17 UTC, andyjiin commented on main.html
> +    				<button class="close" type="button" data-dismiss="modal">x</button>
This button looks kinda ugly I don't think you really need it but maybe you can change it to an `up-arrow` or something

2019-05-19 22:56 UTC, merged